### ISSUE TITLE
Export/save functionality

### ISSUE THREAD

**Issue by hjrnunes** [BurntCaramel/Lantern#3]
Is it possible to save/export the site?

**Comment by royalicing** [comment]
What format would you like? Say CSV?

**Comment by hjrnunes** [comment]
Yep, that would work.

**Comment by thenexus00** [comment]
Hey there,
You did an awesome job with this app - a lot better in many ways then several team based ones that have been produced. Also being a full time developer you can not work on the projects you want too with less spare times (I have kids too so its less then zero!) But do you plan to work on this or continue this project? Export feature here for example would be cool. Would you look to open it up to a team effort to keep it moving along?

**Comment by royalicing** [comment]
Hi @thenexus00 sorry I just saw this! Yes would love to keep working on this. There’s been a bit of hiccups with keeping up to date with the Swift versions, but it’s all stablised now. Yes, plan to keep working on it!

So it sounds like the request would be to export all the crawled pages as CSV? Are there any particular requirements you have here? Thanks for being patient!

**Comment by royalicing** [comment]
@hjrnunes @thenexus00 I have released Lantern version 1.1.0 with CSV exporting of crawled pages. Let me know if it works well for you, and if you have any other requests!
